sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install: 
  - cd 00_RESTWithASP-NET5_ScaffoldViaVS/RESTWithASP-NET5
  - echo "We are in the right folder."
script:
   - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    rest-with-asp-net5:latest $DOCKER_USERNAME/rest-with-asp-net5:$TRAVIS_JOB_ID;
    rest-with-asp-net5-db:latest $DOCKER_USERNAME/rest-with-asp-net5-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net5-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false
